from golang:latest as builder

WORKDIR /app
COPY . .
EXPOSE 8081
RUN GOOS=linux CGO_ENABLED=0 go build   -ldflags="-w -s" -o server .
CMD ["./server"]

from scratch

COPY --from=builder /app/server .
CMD [ "./server" ]